# Site
repository: aaekay/aaekay.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Amit Kumar
title: Medical Doctor, Project Associate
email: amitkumar@aiims.edu
website: www.github.com/aaekay

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: AaekayGarg
github_username:  aaekay
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: aaekayg
linkedin_username: amitkumaraaekay
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Amit and I'm a medical doctor trained at All India Institue of Medical Sciences, Delhi currently working as a project associate at CSIR - IGIB to solve problems that can help clinicians to make more efficient decisions while dealing with the patients.


  My interest includes application of artificial and automated systems in delivering accessible and affordable healthcare.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title:  Steampunk Telegram bot
        link: t.me/aaekay_bot
        caption: Open through mobile phone only
        quote: >
          Open the bot menu to see what this bot can do -helping Indian clinicians to look for availability of genetic tests all over india, helping physcians look for any xray anaomlies with the help of an inegrated ai engine.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way of learning <mark>Python</mark> and intergration of various API available has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content: |
      - layout: left
        title: CSIR - IGIB
        link: https://vinodscaria.rnabiology.org/
        # link_text: boringcompany.com
        sub_title: Project Associate
        caption: February 2022 - Present
        quote: >
          Problems are not defined by the tools you want to use, tools are defined by the problems you want to solve
        description: | # this will include new lines to allow paragraphs
            We solve problems related to rare genetic diseases and ask the questions underlying the genetic information theory.
        
        title: CSIR - IGIB
        link: https://vinodscaria.rnabiology.org/
        # link_text: boringcompany.com
        sub_title: Project Associate
        caption: February 2022 - Present
        quote: >
          Problems are not defined by the tools you want to use, tools are defined by the problems you want to solve
        description: | # this will include new lines to allow paragraphs
            We solve problems related to rare genetic diseases and ask the questions underlying the genetic information theory.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: AIIMS, New Delhi
        caption: 2016 - 2022
        sub_title: Bachelor of Medicine, Bachelor of Surgery
        quote: >
          All-India Institute of Medical Sciences was established as an institution of national importance by an Act of Parliament with the objects to develop patterns of teaching in Undergraduate and Post-graduate Medical Education in all its branches so as to demonstrate a high standard of Medical Education in India; to bring together in one place educational facilities of the highest order for the training of personnel in all important branches of health activity; and to attain self-sufficiency in Post-graduate Medical Education.
        description: | # this will include new lines to allow paragraphs

  - title: Publications # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      Artificial Intelligence–assisted chest X-ray assessment scheme for COVID-19. [link](https://doi.org/10.1007/s00330-020-07628-5)

      Risk factors for Coronavirus disease-associated mucormycosis. [link](https://dx.doi.org/10.1016%2Fj.jinf.2021.12.039)

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in computational biology and healthcare some of my other interests and hobbies are:
      - Badminton
      - Running
      - Cooking
      - Writing blogs

#Look at this cool image  
#![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
